# Generated by Django 2.0.4 on 2018-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20180508_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='email',
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='names',
            name='mobile_phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='names',
            name='work_phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
