# Generated by Django 2.0.4 on 2018-12-28 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180527_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='persona_dep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.Department'),
            preserve_default=False,
        ),
    ]
