# Generated by Django 2.0.4 on 2018-12-28 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20181228_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='persona_dep',
        ),
        migrations.AddField(
            model_name='names',
            name='persona_dep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.Department'),
            preserve_default=False,
        ),
    ]
