# Generated by Django 2.0.4 on 2019-01-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20181228_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='persona_photo',
            field=models.ImageField(default='imgs/nophoto.png', max_length=50, upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='names',
            name='mobile_phone',
            field=models.CharField(max_length=11),
        ),
    ]
