# Generated by Django 2.0.4 on 2019-07-10 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='persona_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.City'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
