# Generated by Django 2.0.4 on 2019-07-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20190710_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='names',
            name='employ',
            field=models.BooleanField(default=False),
        ),
    ]
