# Generated by Django 2.0.4 on 2019-07-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_names_employ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='employ',
            field=models.BooleanField(default=True),
        ),
    ]
