# Generated by Django 2.0.4 on 2019-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_auto_20190712_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='work_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
