# Generated by Django 2.0.4 on 2019-08-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20190812_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alrm_msg_id', models.IntegerField()),
                ('alrm_datetime_start', models.DateTimeField(blank=True, null=True)),
                ('alrm_datetime_end', models.DateTimeField(blank=True, null=True)),
                ('alrm_author', models.IntegerField()),
                ('alrm_city', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
